print("Welcome to the tip calculator.")
total_bill= float(input("What was the total  bill? $"))
percent= int(input("What percentage tip would you like to give? 10,12, or 15? "))
number_people= int(input("How many people to split the bill? "))
print(f"Each person should pay: ${round((total_bill/number_people)*(1+percent/100), 2)}")